version: "2.1"
services:
  db:
    image: postgres
    container_name: rails-api-db 
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=api
    ports:
      - "5432:5432"
  api:
    build: .
    container_name: swapi-api
    depends_on:
      - "db"
    links:
      - "db"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=api
      - POSTGRES_HOST=db
    volumes:
      - "./api:/var/www"
